### ISSUE TITLE
Broken images on some tokens

### ISSUE THREAD

**Issue by Kansuler** [z3us-dapps/z3us#112]
### Prerequisites

* [ ] Can you reproduce the problem in safe mode?
* [X] Are you running the latest version?

For more information, see the `CONTRIBUTING` guide.

### Description

Images of unknown token seem to display as broken links.

### Screenshots

![Screenshot 2022-05-24 at 11 23 51](https://user-images.githubusercontent.com/5369501/169998332-c7e1cb2f-61b7-43e9-90b3-921194827ee1.png)

### Versions
1.0.7

**Comment by zacgodinez** [comment]
@Kansuler Appreciate you logging this one 👍 😀
It shall be fixed.

**Comment by zacgodinez** [comment]
is resolved as a part of this commit https://github.com/z3us-dapps/z3us/commit/e52433b9acbb94d0fad78b7bf5024c9362e9f1b9
👍
