### ISSUE TITLE
SEND APDU failed with underlying error: 'Ledger device: UNKNOWN_ERROR (0x6e01)'

### ISSUE THREAD

**Issue by SpiderParker** [z3us-dapps/z3us#209]
Hello,

I get this error message when I try to connect my Ledger to Zeus :

"SEND APDU failed with underlying error: 'Ledger device: UNKNOWN_ERROR (0x6e01)'"

I'm running the latest version of Zeus because I've just installed it

**Comment by SpiderParker** [comment]
Problem solved

**Comment by heathsnee** [comment]
Could you just let us know how did you solve the issue ? It is good to post resolution for other users to find in case they experience the same thing.

**Comment by SpiderParker** [comment]
I think that the problem was just that my Ledger wasn't recgnized by my computer
I reconnected the Ledger and unlocked it ans everything worked

**Comment by heathsnee** [comment]
Ok, thanks for letting us know. I am closing this issue

**Comment by SpiderParker** [comment]
Edit : The problem is appearing again.

i connected my Nano X to my laptop using Thunderbolt (Type C) and I well opened Radix app.

**Comment by heathsnee** [comment]
Try restarting browser, or reinstalling wallet if that help. If not, we will need a little bit more details please.
