### ISSUE TITLE
Why did you uninstall ?

### ISSUE THREAD

**Issue by khademreza688** [z3us-dapps/z3us#361]
### Discussed in https://github.com/z3us-dapps/z3us/discussions/150

<div type='discussions-op-text'>

<sup>Originally posted by **heathsnee** June 18, 2022</sup>
## 👋 Welcome!

  We would like to get your feedback:

  * Why did you uninstall?
  * Is there anything we can do?

  To get started, comment below with an introduction of yourself and tell us about what was your experience with our wallet.</div>

**Comment by heathsnee** [comment]
Closing this issue, we will track this differently
